apiVersion: V1
kind: Service
metadata:
  name: Loadbalancer-svc
spec:
  type:LoadBalancer
  selector:
    app: hello
  port:
     - name: http
       protocol: TCP 
       port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-pod
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: hello
  template:
    metadata:
      labels: 
        app: hello
    spec:
      containers:
        - name: hello
          image: Greenpearl123/june9test:latest
          imagePullPolicy: Always
